### ISSUE TITLE
Don't store API key in the component settings

### ISSUE THREAD

**Issue by daftspunk** [rainlab/mailchimp-plugin#1]
It's not the smartest idea to store the Mailchimp API key in the Component settings area. This file might be compromised.

The API key should be stored in the database or at least in an encrypted format.

**Comment by alekseybobkov** [comment]
Yes, the DB is the appropriate place. The same goes for any credentials. Perhaps we should extend the Settings API with the column encryption feature.

**Comment by daftspunk** [comment]
This is complete, Settings model is now used.
