### ISSUE TITLE
AJAX handler 'mailSignup::onSignup' was not found.

### ISSUE THREAD

**Issue by Michael-Brooks** [rainlab/mailchimp-plugin#10]
I have a clean install of October and installed the Mailchimp plugin. I have added the component from the components list and inserted the code. Tried to test with my own email and the alert above was shown.

**Comment by svetbg** [comment]
I have exactly the same issue.

**Comment by svetbg** [comment]
May be this helps:
https://github.com/rainlab/mailchimp-plugin/issues/2

**Comment by daftspunk** [comment]
Duplicate of #2 

See http://octobercms.com/docs/cms/partials#life-cycle-limitations

**Comment by alinalamichhane** [comment]
If you include the component in partial, you also have you include the same component in the layout in which you're including that partial. Worked for me. Hope it helps.
