### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by pagliaso** [rainlab/mailchimp-plugin#11]
Hi,

Is it possible to translate this good plugin to Spanish? Could I help?

Many thanks and kind regards,

Alb

**Comment by LukeTowers** [comment]
First we'd have to get it using localization to begin with, then adding a Spanish language file would be relatively simple. See http://octobercms.com/docs/plugin/localization for more information.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
