### ISSUE TITLE
AJAX handler mailSignup::onSignup not found

### ISSUE THREAD

**Issue by jmondragon** [rainlab/mailchimp-plugin#12]
I can't seem to get this working.  I've got the component added and configured with API key and List ID, but anytime I try to enter an email on the front end, the AJAX framework comes back with an error that onSignup is not found, however when I go into the source code for the plugin, I can see that there is a function called onSignup.

It looks like a pretty straight forward plugin, so I'm not sure what I could be missing.

Thank you,
Josh

**Comment by daftspunk** [comment]
Make sure you are adding the component to a layout or page, not a partial. Partials have limitations with AJAX, see the documentation for more details.

**Comment by jmondragon** [comment]
Perfect.  Thank you, that was it.
