### ISSUE TITLE
MCAPI.class.php PHP 7 Compatibility 

### ISSUE THREAD

**Issue by furqanfreed** [rainlab/mailchimp-plugin#14]
PHP 4 style constructors Deprecated in PHP 7.0.x

so update 

```
function MCAPI($apikey, $secure=false) {
        $this->secure = $secure;
        $this->apiUrl = parse_url("http://api.mailchimp.com/" . $this->version . "/?output=php");
        $this->api_key = $apikey;
    }
```

TO:

```
function __construct($apikey, $secure=false) {
        $this->secure = $secure;
        $this->apiUrl = parse_url("http://api.mailchimp.com/" . $this->version . "/?output=php");
        $this->api_key = $apikey;
    }
```

**Comment by LukeTowers** [comment]
Perhaps we should switch to using https://bitbucket.org/mailchimp/mailchimp-api-php

**Comment by marcoelho97** [comment]
@daftspunk That little MCAPI function was preventing all users in my website from subscribing... :(
Started getting an error when I went to a new server..
![image](https://user-images.githubusercontent.com/13586621/30118445-ff32aee2-931a-11e7-91d5-69f0b8ff8b13.png)

**Comment by LukeTowers** [comment]
@marcoelho97 apply the fix from develop, I'll talk to @daftspunk about pushing a new update to the marketplace.
