### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by tobyhage** [rainlab/mailchimp-plugin#16]
Hello,

I'am trying this plugin, but without success.

I have filled in the Mailchimp API key.
I have added component with {% component 'mailSignup' %} + List id to page: http://october.droneshoponline.nl/nieuws

When i fill in email address + subscribe nothing happens, what am i doing wrong?

Or how can i debug?

Hopefully someone can help me with this.

**Comment by daftspunk** [comment]
Looks like you may need to include the `{% framework %}` tag on your page / layout.

**Comment by tobyhage** [comment]
Thanks, now it is working.
