### ISSUE TITLE
Double opt-in doesn't seem to work

### ISSUE THREAD

**Issue by IvanRibakov** [rainlab/mailchimp-plugin#18]
Using plugin to add subscribers to the list. Subscribers get added, but no opt-in confirmation is sent. Neither subscription notifications are being sent. Waiting overnight, still no emails received (opt-in conf nor subscription notification). Domain from which emails appear to be send is verified in MailChimp. Any suggestions on what I may be missing?

**Comment by LukeTowers** [comment]
Opt in confirmation emails are normally sent by Mailchimp itself, are your settings correct?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by Eoler** [comment]
There's one parameter that needs to be configurable to force double opt-in confirmation from MailChimp:
https://stackoverflow.com/questions/31251271/realize-mailchimp-double-opt-in-with-api-3-0

We poor Europeans require it for GDPR, so I can do PR to "unabandon" this issue...

**Comment by LukeTowers** [comment]
@Eoler go for it!

**Comment by Eoler** [comment]
Here we go: #26

**Comment by LukeTowers** [comment]
Awesome, thanks @Eoler! Merged in https://github.com/rainlab/mailchimp-plugin/commit/36de424a40e39b002b989c0decc12718c26fa08e
