### ISSUE TITLE
AJAX handler 'mailSignup::onSignup' was not found

### ISSUE THREAD

**Issue by daveharrisonnet** [rainlab/mailchimp-plugin#2]
component has been added to footer partial . I get the following error everytime I submit the form
AJAX handler 'mailSignup::onSignup' was not found

Is this broken after RC upgrade or perhaps I have implemented it wrong?
All help welcome

I should add I am using override for the partials (in case upgrades overwrite my design changes)
But I have tried with default partials from plugin/component/ folder too and same result

**Comment by myxsys** [comment]
Me too. I also placed the the component in the footer partial and it shows the error 'mailSignup::onSignup'. However, if I put it in the layout page, it works but the success message gets displayed as a popup

**Comment by daveharrisonnet** [comment]
So I moved the component directly onto the page instead of my footer partial. Now it will handle the ajax stuff, but it is throwing up an error - Sorry there was an error: Invalid MailChimp API Key. The API key I am using is definately correct, I have placed it both on the component and also in settings in the backend neither works. Does the pluging still work for anyone else or perhaps mailchimp have moved the goalposts and the plugin needs updated??

**Comment by daveharrisonnet** [comment]
OK well I have now figured out you need to create an API key to enter in mailchimp settings in the backend as well as your list ID to enter in the component instance. However having successfully done all this and got the ajax stuff to work with both error messages and succes message I am seeing that no emails are actually being added to my list! unless there is a delay for new subscribers using API? Watch this space!.....

**Comment by daveharrisonnet** [comment]
Ok Sorry it's been a long day, of course the emails weren't being added because they were double optin and i hadn't confirmed the subscriptions. All is working now ;) 

But can I add this component to my partial or is there a way to do that?

**Comment by jasonlfunk** [comment]
I'm also having this problem. It's not an option for me to put it in the layout page instead of a partial. Is there a way to get around this?

**Comment by jasonlfunk** [comment]
Apparently it has to do with the fact that complex components don't work in partials.

http://octobercms.com/docs/cms/partials#life-cycle-limitations

**Comment by daftspunk** [comment]
Try adding the component to the layout. Partials don't support AJAX since they are rendered late in the page cycle.

**Comment by abishekrsrikaanth** [comment]
I am getting this error even when I set this up on the layout.

**Comment by preinmann** [comment]
I'm getting the same 'mailSignup::onSignup' was not found' message. Has there been a solution that works? I've tried to add the component to the layout - same issue. Thanks!

**Comment by frthjf** [comment]
@daftspunk I ran into the partial issue as well, maybe it is worth mentioning in the plugin documentation?

**Comment by daftspunk** [comment]
Documentation exists already: http://octobercms.com/docs/cms/partials#life-cycle-limitations

Feel free to submit a PR to this repo to mention it in the plugin docs.

**Comment by GregorioLopez** [comment]
> 
> 
> I'm also having this problem. It's not an option for me to put it in the layout page instead of a partial. Is there a way to get around this?

I put the component declaration [Signup] at the layout, but the component form at my sidebar.htm partial and it works.

**Comment by pujak17** [comment]
> component has been added to footer partial . I get the following error everytime I submit the form
> AJAX handler 'mailSignup::onSignup' was not found
> 
> Is this broken after RC upgrade or perhaps I have implemented it wrong?
> All help welcome
> 
> I should add I am using override for the partials (in case upgrades overwrite my design changes)
> But I have tried with default partials from plugin/component/ folder too and same result

If you include the component in partial, you also have you include the same component in the layout in which you're including that partial. Worked for me. Hope it helps.
