### ISSUE TITLE
Subscription not working

### ISSUE THREAD

**Issue by mariavilaro** [rainlab/mailchimp-plugin#24]
It doesn't return an error, but when debugging the code I find that the call to the API returns this:

HTTP/1.0 302 Moved Temporarily\r\n
Server: AkamaiGHost\r\n
Content-Length: 0\r\n
Location: https://us19.api.mailchimp.com/1.3/?output=php&method=listSubscribe\r\n
Date: Wed, 08 Aug 2018 15:00:04 GMT\r\n
Connection: close\r\n
\r\n

any idea what's happening?

**Comment by LukeTowers** [comment]
@mariavilaro can you replicate this on a fresh install with a different mailchimp account?

**Comment by mariavilaro** [comment]
Yes, I just checked with a clean install and another account, this is a `dd($response);` on MCAPI.class.php line 2888 

HTTP/1.0 302 Moved Temporarily\r\n
Server: AkamaiGHost\r\n
Content-Length: 0\r\n
Location: https://us12.api.mailchimp.com/1.3/?output=php&method=listSubscribe\r\n
Date: Thu, 09 Aug 2018 14:52:18 GMT\r\n
Connection: close\r\n

**Comment by LukeTowers** [comment]
@mariavilaro looks like MailChimp finally got around to fully removing the 1.3 API: https://www.drupal.org/project/mailchimp/issues/2189665. Would you be willing to provide a PR to switch to V3 of the API, probably using https://github.com/drewm/mailchimp-api through composer?

**Comment by mariavilaro** [comment]
I'm in it!

**Comment by LukeTowers** [comment]
Awesome, thanks @mariavilaro!
