### ISSUE TITLE
Not able to link website with mailchimp

### ISSUE THREAD

**Issue by Mins17** [rainlab/mailchimp-plugin#27]
Hi, I am trying to integrate mailchimp plugin. I have entered the mailchimp list id and entered the mail chimp API key. 
When i enter an email address and press subscribe button. It does nothing and place the email address in the address bar of the chrome.
Kindly help.
Tell me what step am i missing here.

**Comment by LukeTowers** [comment]
Did you check your console for errors? Are you properly including jQuery and the OctoberCMS AJAX framework in your frontend?

**Comment by Mins17** [comment]
in the console i don't see any errors.
I write a mail address in the form and then i press the subscribe button, the page refreshes and in the url bar, the email address is written as - "abc.com/?email=xyz%40gmail.com"

i have added jquery in the head tags
in the body part i've added-> {% framework %} {% page %}
please tell if i need to add anything more.

**Comment by LukeTowers** [comment]
@Mins17 Do you have a live site up with the issue? You might have better luck asking for help on the slack

**Comment by Mins17** [comment]
Yes i have a live site. Can you please help me, if I am missing some code here or have i not included some pre requisite to make this plugin work?

**Comment by Mins17** [comment]
Hi, I have tested the plugin on different pages of my website, the plugin works smoothly but its not working only on the main front page of my website. Everything is same in all other pages the only difference being the user front end management plugin in the main front page.

**Comment by LukeTowers** [comment]
Got a link to it?

**Comment by Mins17** [comment]
http://www.vizmins.com

**Comment by LukeTowers** [comment]
@Mins17 I don't really have time to debug your specific case, I recommend you try the Slack group instead.

**Comment by Mins17** [comment]
Thanks for your time.

**Comment by Mins17** [comment]
Hi Luke, it was a mistake from my side. The plugin works perfectly. Thanks. You can close this issue.
