### ISSUE TITLE
Error when submitting

### ISSUE THREAD

**Issue by mabehiry** [rainlab/mailchimp-plugin#28]
This is the error:
Sorry there was an error: 404: The requested resource could not be found.
It seems that this link no longer exist:
$result = $MailChimp->post("lists/".$this->property('list')."/members", $subscriptionData);

**Comment by tylkosprawdzam** [comment]
@mabehiry
I'm having the same issue. Did You manage to figure out how to fix it?

**Comment by tylkosprawdzam** [comment]
The problem was reading components property - list. Even though I've added it to component properties it didn't work, so I changed the line
`$result = $MailChimp->post("lists/".$this->property('list')."/members", $subscriptionData);`
to
`$result = $MailChimp->post("lists/".$listId."/members", $subscriptionData);`
where `$listId` is a hardcoded id of the list, and now it works properly.

**Comment by LukeTowers** [comment]
@tylkosprawdzam not great to hard code it because that will be removed the next time this updates. Please post the component configuration in the template file that wasn't working.

**Comment by freeyland** [comment]
I have the same issue. How did you resolve?

**Comment by Hessel91** [comment]
same issue

**Comment by Hessel91** [comment]
> The problem was reading components property - list. Even though I've added it to component properties it didn't work, so I changed the line
> `$result = $MailChimp->post("lists/".$this->property('list')."/members", $subscriptionData);`
> to
> `$result = $MailChimp->post("lists/".$listId."/members", $subscriptionData);`
> where `$listId` is a hardcoded id of the list, and now it works properly.

I changed the solution you mentioned, however, it throws a new error : 
"Undefined variable: listId" on line 75 of C:\xampp\htdocs\mommy\plugins\rainlab\mailchimp\components\Signup.php"

**Comment by daftspunk** [comment]
Hello @Hessel91, The suggested change is not reliable. Please make sure you have a `list` property set in your component configuration that contains the Mailchamp List ID. 

I hope this helps!

**Comment by Hessel91** [comment]
there was a dot (.) copied from my Mailchimp account behind my list id. that was the true issue. thank you for your reply @daftspunk for clearing this issue.  This plugin works just fine.
