### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Dione-stack** [rainlab/mailchimp-plugin#33]
Hello! i'm receiving this error from signup form: `Sorry there was an error: Unknown error, call getLastRespomse() to find out what happened ` do you have any idea how to fix it?

**Comment by LukeTowers** [comment]
Sounds like an issue with MailChimp, try googling for the error message.

**Comment by Dione-stack** [comment]
thank you for taking the time to reply.
You're right, i managed to fix it but now i'm receiving another error: `Sorry there was an error: 404: The requested resource could not be found.`

Someone has already opened an issue about it #28 and this was your respond:
> not great to hard code it because that will be removed the next time this updates. Please post the component configuration in the template file that wasn't working.

I do not understand this solution, which template file? are you talking about extending component to another custom plugin to avoid losing code when rainlab's mailchimp-plugin gets updated? please clarify

**Comment by LukeTowers** [comment]
@Dione-stack that error probably indicates something is wrong with the information you provided the component. I was asking for the person to post the template file that they included the component on which includes the component's configuration at the top.

**Comment by Dione-stack** [comment]
I'm sure the API key is correct, i'm suspicious about MailChimp List ID, is that required?

**Comment by LukeTowers** [comment]
@Dione-stack it is required, it sounds like you've given it an incorrect List ID, or at the very least one that your API key doesn't have access to.

**Comment by Dione-stack** [comment]
yes, the **MailChimp List ID** is required after all, it's not incorrect i didn't provide it in the first place, it's called **Audience ID** now, that made me confused i couldn't find it in my MailChimp account settings

The problem was much simple than i thought, everything is working perfectly now, thank you for everything
