### ISSUE TITLE
Is this plugin mantained?

### ISSUE THREAD

**Issue by mariavilaro** [rainlab/mailchimp-plugin#37]
We use it in almost all of our October projects, and I see that it seems deprecated (in the october marketplace it's only compatible with october 1, even if we are using it withoug problems with 2 and 3 projects). I'd like to subscribe users in mailchimp when they register (if they check a newsletter subscription checkbox), and I'm wondering if I should do a pull request here or if maybe I should develop my own new Mailchimp plugin.

**Comment by daftspunk** [comment]
Hey @mariavilaro 

We no longer use it internally, opting to use the [Campaign plugin instead](https://octobercms.com/plugin/responsiv-campaign), but if you have tested it with v2 and v3, we can use this compatibility information to update it. Regarding new features, this plugin serves as an example for integrating with third-party services, so we prefer to keep it simple. You could create another plugin to include this functionality--based on this one, or by extending this one.

**Comment by mariavilaro** [comment]
Yes, it works with OC2 and 3, you can update the compatibility info.

I need to subscribe the users to mailchimp when they sign up (if they check the "subscribe" option), so I need to develop an extension of the User plugin that adds a new field "subscribe_to_newsletter" and does the subscription when the register or update events are thrown, and this field is filled. The problem is that, as this plugin has all the subscription logic in the component, I cannot use it, I need to duplicate it in my plugin. Can I do a PR to extract this logic below "Sign up to Mailchimp via the API" into a class so it can be called from the component but also from other plugins? Will you accept it?

**Comment by daftspunk** [comment]
No problem. Make a PR with your requirements and we can take a look.
