### ISSUE TITLE
Accessing result of signin up from fron side

### ISSUE THREAD

**Issue by A8-Utopig** [rainlab/mailchimp-plugin#39]
Hello,

I have tried displaying different messages on the frontend depending on the result of executing the onSignup() function, however this function does not return the result directly. I've created a pull request to fix this so that it's easy to grab the status field (or any other) on the front side and do whatever you need with it.

The pull request is [here](https://github.com/rainlab/mailchimp-plugin/pull/38).

**Comment by daftspunk** [comment]
Fixed by #38

**Comment by mariavilaro** [comment]
Hi @daftspunk ! I can see that the PR that fixes this is merged, it's not in the published plugin yet, can you please release a new version? Thks :)

**Comment by daftspunk** [comment]
Done
