### ISSUE TITLE
"You must specify a id value for the listSubscribe method" error

### ISSUE THREAD

**Issue by frthjf** [rainlab/mailchimp-plugin#9]
Using the proposed form snippet from the docs I get an error message:
"Sorry there was an error: You must specify a id value for the listSubscribe method"

Any ideas about that?

**Comment by frthjf** [comment]
Found the problem. I defined the list property in a partial, so `$this->property('list')` returned `null`. I configured the list value in the layout now and it works. However, why is it not possible to put the newsletter logic to a partial?

**Comment by flydev-fr** [comment]
@dudheit314 How do you use the list ID ?  because i am getting this error too and I am not using it in a partial but in my default layout.
![capture](https://cloud.githubusercontent.com/assets/11658616/12538052/8e9f2150-c2cf-11e5-930d-bd597a70bc2b.PNG)

**Comment by frthjf** [comment]
@desaparecido I am not sure whether I got you right, but here is the working code which I put directly (so no snippets etc.) to the page layout:

```
<form class="form-inline" data-request="{{ mailSignup }}::onSignup" data-request-update="'newsletter-signup-success': '#subscribe-form'">
<input name="email" placeholder="E-Mail" class="form-control" type="email">
<button type="submit" class="btn btn-primary">Send</button>
</form>
```

I think you have to click on the icon in the list ID field, it should be on the right side, when you fill it.
 And by the way, I think it is not the best idea to publish the ListID here.

**Comment by flydev-fr** [comment]
When I use the component in the backend to setup the list ID, I got the error; But if I hardcode the ID list in the MCAPI class php file, it works.  Thanks you for replying so fast.

**Comment by frthjf** [comment]
I think there is no need to hardcode the ID into the MCAPI class. You can also define the ListID in the layout file directly:

```
description = "Homepage layout"
[staticPage]
[mailSignup]
list = "0f92...3e4"
==
<html> ...
```

**Comment by flydev-fr** [comment]
Still not working, only the hardcoding way is working at this moment.

I will try with a fresh install.

**Comment by rossity** [comment]
for anyone still having this issue:
when you use the GUI to set the list ID it sets it like this:
```
[mailSignup]
list = {{ "e521e2dd76" }}
```
change it to this
```
[mailSignup]
list = "e521e2dd76"
```
This worked for me.
